version: '3'


services:

  server:
    build: .
    command: ./api
    restart: always
    container_name: api_server
    ports:
      - 9000:9000
    networks:
      - gateway_network
      - raggitmq_network
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6
    container_name: api_mongo
    ports:
      - 27017:27017
    env_file:
      - ./pkg/config/envs/prod.mongo.env


networks:
  gateway_network:
    external: true
  raggitmq_network:
    external: true