version: '3'

services:

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./X-MAS-FRONT
    command: serve -s build
    restart: always
    container_name: frontend_client
    volumes:
      - X-MAS-FRONT/node_modules