version: '3'


services:

  server:
    build: .
    restart: always
    container_name: ml_server
    command: python3 main.py
    env_file:
      - ./config/prod.rabbitmq.env
    networks:
      - raggitmq_network


networks:
  raggitmq_network:
    external: true