name: ml-tests
on:
  push:
    paths:
      - .github/workflows/ml-tests.yml
      - backend/ml/**

defaults:
  run:
    working-directory: ./backend/ml

jobs:
  ml-tests:
    tika:
      image: apache/tika:2.5.0
      ports:
        - 9998:9998

    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache Tox (pip)
        uses: actions/cache@v2
        id: cache-tox
        env:
          cache-name: cache-pip-tox
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Tox
        if: ${{ steps.cache-tox.outputs.cache-hit == false }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install tox==4.0.16

      - name: Cache lint
        uses: actions/cache@v2
        id: cache-lint
        env:
          cache-name: cache-lint
        with:
          path: |
            .tox/lint/**
            !.tox/lint/log/**
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.tox/lint/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Lint
        run: python3 -m tox -e lint

      - name: Cache typing
        uses: actions/cache@v2
        id: cache-typing
        env:
          cache-name: cache-typing
        with:
          path: |
            .tox/typing/**
            !.tox/typing/log/**
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.tox/typing/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Typing
        run: python3 -m tox -e typing

      - name: Cache tests
        uses: actions/cache@v2
        id: cache-tests
        env:
          cache-name: cache-tests
        with:
          path: |
            .tox/py39/**
            !.tox/typing/log/**
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.tox/py39/**') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Tests
        run: python3 -m tox -e py310